version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: build/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony
        ports:
            - 80:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: build/php/Dockerfile
            args: 
                TIMEZONE: ${TIMEZONE}
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        volumes:
            - "./mysql:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
networks: 
    symfony: